### ISSUE TITLE
Comparison to similar projects?

### ISSUE THREAD

**Issue by boblehest** [oxalica/rust-overlay#139]
As a prospective user of this overlay, I'm curious what its relation is to [nix-community/fenix](https://github.com/nix-community/fenix) (and any other alternatives that might exist). My impression is that they serve similar needs, but I see that Fenix was created literally one day after this repository (both in January 2021), so it's likely both projects were started without any knowledge of the other.

When I see no mention of similar projects in the readme of this repository, I worry that there is a needless division of a community who could have been working towards the same goal. Has anyone compared them? (Do they have different goals / implementations / use cases?)

**Comment by sauricat** [comment]
The foss community would be happy to see different implements of similar functions. It increases the liability despite its efficiency, but everyone could work on their preferred projects, couldn't it? Just follow your judgment and choose the one you prefer, be its user and contribute to it.

**Comment by oxalica** [comment]
> When I see no mention of similar projects in the readme of this repository, 

>  it's likely both projects were started without any knowledge of the other.

I'd say yes, we discovered each other after the publish.

> I worry that there is a needless division of a community who could have been working towards the same goal.

As mentioned by @sauricat, diversity is a good thing. Healthy competition should benefits all users and covers more use cases without a monopoly.

>  Has anyone compared them? (Do they have different goals / implementations / use cases?)

 (DISCLAIMER: I don't use fenix personally. Correct me if I get it wrong)

The main difference to me is that rust-overlay is designed as a replacement to [nixpkgs-mozilla](https://github.com/mozilla/nixpkgs-mozilla) in the first place. The original interface is kept for compatibility and the new one is also kinda alike. The most important functionality is to arbitrarily[^1] select any historical stable, nightly, or beta version, with their components. You can pick up, say nightly-2023-01-02, for a specific nightly project which is enforces the toolchain version (like rustc itself). Older stable version can also be used for MSRV tests or bisecting.

AFAIK, [fenix](https://github.com/nix-community/fenix) is designed from ground up to be a simpler always-up-to-date toolchain provider for users who "just want to get a latest Rust". They also more emphasize the (currently still unstable) flake interface. If you don't care about historical Rust and/or specific nightly versions, fenix is probably simpler, smaller and good enough for you.

Despite the name of rust-overlay, we also can be used as a flake[^2] instead of an overlay, though the interface is not stable and less documented, just like the flake feature itself.

There's also more info in discorse for [rust-overlay](https://discourse.nixos.org/t/rust-overlay-a-better-rust-toolchain-provider-and-drop-in-replacement-of-nixpkgs-mozilla/10986/18) and [fenix](https://discourse.nixos.org/t/fenix-rust-toolchains-for-all-channels-and-rust-analyzer-nightly/13040).

[^1]: Up to 1.29.0/2018-09-13 currently, said in README.
[^2]: Currently the interface is like `github:oxalica/rust-overlay#rust-nightly_2023-01-02` or `github:oxalica/rust-overlay#rust_1_72_1`.
