### ISSUE TITLE
List of default/all available extensions

### ISSUE THREAD

**Issue by nathanshelly** [oxalica/rust-overlay#14]
Thanks for the overlay! Loving the flake dev experience with it.

Two questions:

- What are the default extensions that come with `rust-bin`?
- How can I see which extensions are available for my platform/targets?

I see two comments in `rust-overlay.nix` which seem to suggest the same default set:

https://github.com/oxalica/rust-overlay/blob/e97d64daac9333196691e776d5062713a79bf951/rust-overlay.nix#L293-L308
https://github.com/oxalica/rust-overlay/blob/e97d64daac9333196691e776d5062713a79bf951/rust-overlay.nix#L381-L388

Both those comments mention `rust-src` though, which I find that I need to manually specify via `.override` in order for `rust-analyzer` to find it:

```nix
pkgs.rust-bin.nightly.latest.rust.override {
  extensions = [ "rust-src" ];
};
```

I see that the toolchain is generated from the various manifest files (I'm currently using the `02-06` nightly so I assume it's using [this manifest](https://github.com/oxalica/rust-overlay/blob/e97d64daac9333196691e776d5062713a79bf951/manifests/nightly/2021/2021-02-06.nix#L1)) but I don't understand how to interpret that.

I also see these lines which appear to be the list of all available extensions:

https://github.com/oxalica/rust-overlay/blob/e97d64daac9333196691e776d5062713a79bf951/manifest.nix#L10-L30

When I try to add `rustfmt-preview` I get the following error:

```console
> nix develop
While compiling rust: the extension rustfmt-preview is not available.
Select extensions from the following list:
clippy-preview
rust-analyzer-preview
llvm-tools-preview
rust-analysis
rust-std
rustc-dev
rustc-docs
rust-src
```

Is that expected on macOS or is there something I'm doing wrong here?

**Comment by oxalica** [comment]
> What are the default extensions that come with rust-bin?

`pkgs.rust-bin.nightly.latest.rust` is an aggregated "component" provided by upstream. What components it has also depends on upstream.
But it usually has `cargo`, `rustc`, `rustdoc`, `miri`, `rls`, `rust-analyzer`, `rustfmt`, `clippy` and almost all binaries which seems enough for common users. (But `rust-src` is not contained by default)

> How can I see which extensions are available for my platform/targets?

Currently, no, except typing an non-existent component to get the error message like what you do.
We may add a more convenient way to do that in the future.

> Is that expected on macOS or is there something I'm doing wrong here?

You did nothing wrong. It's simply because rust nightly 2021-02-06 actually does **NOT** have `rustfmt` built. Note that nightly releases don't always have all common components built (successfully) due to rustc internal changes.

You can check this site for avilability of components in each nightly releases, and pick an older release which contains all components you need.
https://rust-lang.github.io/rustup-components-history/

**Comment by nathanshelly** [comment]
Thank you so much for the thorough response!
