### ISSUE TITLE
Add rustc-codegen-cranelift component to rust-overlay for nightly

### ISSUE THREAD

**Issue by benwis** [oxalica/rust-overlay#142]
Apologies if there is some way to do this I'm missing, but I'm trying to add rustc-codegen-cranelift as a component, as it's included in the latest nightly. Since it's very new, I don't think it's included.

Can I get that added?

**Comment by oxalica** [comment]
Enabling `extensions = [ "rustc-codegen-cranelift" ]` should work. But right now, there are some issues upstream that it contains only documentations but no backend DLL. See https://github.com/rust-lang/rust/pull/81746#issuecomment-1783888093. The next nightly release since https://github.com/rust-lang/rust/pull/117328 should make it work.

**Comment by oxalica** [comment]
2023-10-31 is out with the fix. Now this works under master:
```nix
rust-bin.nightly."2023-10-31".minimal.override {
  extensions = [ "rustc-codegen-cranelift-preview" ];
}
```
I verified that `rustc -Zcodegen-backend=cranelift` compiles and runs flawlessly. :tada:

**Comment by benwis** [comment]
> 2023-10-31 is out with the fix. Now this works under master:
> 
> ```nix
> rust-bin.nightly."2023-10-31".minimal.override {
>   extensions = [ "rustc-codegen-cranelift-preview" ];
> }
> ```
> 
> I verified that `rustc -Zcodegen-backend=cranelift` compiles and runs flawlessly. 🎉

Indeed it does, it works with just `rustc-codegen-cranelift` as well. Thanks for looking into it!
