### ISSUE TITLE
unable to replace nixpkgs-mozilla/rust-overlay with rust-overlay/rust-overlay: fails to evaluate

### ISSUE THREAD

**Issue by zserik** [oxalica/rust-overlay#15]
I tried to port https://github.com/zserik/crulz-rs/blob/8af30249e8b2a21da27d48037b713411e20b79d0/nix/nixpkgs.nix to this `rust-overlay`, but it doesn't work...
Trace: https://github.com/zserik/crulz-rs/blob/cc2c168498eba53f00014ccd5f57357d891893f3/nix_trace.txt
"eval error: attribute 'rust-bin' missing"
Applied changes (wrapper `nixpkgs.nix`): https://github.com/zserik/crulz-rs/commit/cc2c168498eba53f00014ccd5f57357d891893f3#diff-7b06b62d006ecf7b5a6cd3623976d7a6f1522bb1208ae904f0501347faee6b5d

**Comment by oxalica** [comment]
> `rustChannelsOverlay = import "${sources.rust-overlay}/rust-overlay.nix";`
https://github.com/zserik/crulz-rs/commit/cc2c168498eba53f00014ccd5f57357d891893f3#diff-7b06b62d006ecf7b5a6cd3623976d7a6f1522bb1208ae904f0501347faee6b5dR3

You should import from `default.nix` or simply `import sources.rust-overlay`.
Because this repo contains only a single overlay so it is exported as default, while `nixpkgs-mozilla` has many different overlays for firefox, rust and etc. 

This is mentioned in README that you can get the overlay by simply importing the repo (source) without any sub-paths.
https://github.com/oxalica/rust-overlay#use-as-a-classic-nix-overlay

Other nix files are only for internal code organization. You should not directly import them.
But maybe we could rename `rust-overlay.nix` and make a compat wrapper (with a warning) for the common importing path of `nixpkgs-mozilla`.

**Comment by zserik** [comment]
Is
```nix
let
  sources = import ./sources.nix;
  rustChannelsOverlay = import sources.rust-overlay;
```
correct, or should it be the following?
```nix
let
  sources = import ./sources.nix;
  rustChannelsOverlay = sources.rust-overlay;
```

**Comment by oxalica** [comment]
I saw `import sources.nixpkgs` below. Maybe `sources.<name>` is a path?
If so, it should be `rustChannelsOverlay = import sources.rust-overlay;`

**Comment by zserik** [comment]
Maybe. I realised that the rustc version in nixpkgs is recent enough, thus I won't require the overlay anymore.
