### ISSUE TITLE
Flakes aarch64-darwin support

### ISSUE THREAD

**Issue by eugkhp** [oxalica/rust-overlay#157]
I'm trying to use this repo as a go to for rust development, but I'm new to nix and can't figure out how to use flakes. 

For some reason when I add to my `.envrc` `use flake github:oxalica/rust-overlay` - nothing happens, `cargo --version` prints command not found.

If I add a commit  hash `use flake github:oxalica/rust-overlay#8dfbe2dffc28c1a18a29ffa34d5d0b269622b158` it prints 

```
direnv: loading ~/projects/zero2prod/.envrc
direnv: using flake github:oxalica/rust-overlay#8dfbe2dffc28c1a18a29ffa34d5d0b269622b158
error: flake 'github:oxalica/rust-overlay' does not provide attribute 'devShells.aarch64-darwin.8dfbe2dffc28c1a18a29ffa34d5d0b269622b158', 'packages.aarch64-darwin.8dfbe2dffc28c1a18a29ffa34d5d0b269622b158', 'legacyPackages.aarch64-darwin.8dfbe2dffc28c1a18a29ffa34d5d0b269622b158' or '8dfbe2dffc28c1a18a29ffa34d5d0b269622b158'
```

Same happens if I use `nix develop`
```
nix develop github:oxalica/rust-overlay              
Evgeniis-MacBook-Pro:zero2prod eugkhp$ cargo --version
bash: cargo: command not found
```
however, the `shell` works fine:
```
 nix shell github:oxalica/rust-overlay                
 ~/projects/zero2prod  main +113 !36 ?2728 cargo --version                                          
cargo 1.76.0 (c84b36747 2024-01-18)
```

Am I doing something wrong or there is no support for arm in flakes?

**Comment by oxalica** [comment]
> use flake github:oxalica/rust-overlay#8dfbe2dffc28c1a18a29ffa34d5d0b269622b158

After `#` is the flake attrpath for eval, not the commit hash.

> For some reason when I add to my `.envrc` `use flake github:oxalica/rust-overlay` - nothing happens, `cargo --version` prints command not found.

This loads the development environment for building (actually downloading) rust itself, which is unhelpful. Since `use flake <url>` loads `<url>`'s development environment `<url>#devShells.default`, instead of adding its output packages to PATH. You need to create your own `flake.nix` under current directory with your `devShells` defined, which is [demonstrated in README](https://github.com/oxalica/rust-overlay?tab=readme-ov-file#use-in-devshell-for-nix-develop), and then `use flake .`. See also https://github.com/nix-community/nix-direnv/issues/163 . I don't know if there's a easy way for `direnv` to bring a flake output package into environment.

Alternatively, we can provides `devShells` as devshells with `rust` inside. But this is also counter-intuitive since it's expected that `<url>#devShells` are shells for developing `<url>` itself, eg `github:NixOS/nix#devShells.default` contains a environment for building `nix` , not using `nix`.
