### ISSUE TITLE
Add flake examples for cross-compilation

### ISSUE THREAD

**Issue by holly-hacker** [oxalica/rust-overlay#163]
For the past hour I've been trying to convert the cross-aarch64 example to a flake, to no avail. It'd be nice if an example of this was provided.

**Comment by zhpjy** [comment]
I use nix-direnv, and following flake.nix works.
``` cargo run --target aarch64-unknown-linux-musl ``` to run and ``` cargo build --release --target aarch64-unknown-linux-musl ``` to build aarch64 bin file
```
{
  description = "A Nix-flake-based Rust development environment";

  inputs = {
    nixpkgs.url = "https://flakehub.com/f/NixOS/nixpkgs/0.1.*.tar.gz";
    rust-overlay = {
      url = "github:oxalica/rust-overlay";
      inputs.nixpkgs.follows = "nixpkgs";
    };
  };

  outputs = { self, nixpkgs, rust-overlay }:
    let
      overlays = [
        rust-overlay.overlays.default
        (final: prev: {
          rustToolchain =
            let
              rust = prev.rust-bin;
            in
            if builtins.pathExists ./rust-toolchain.toml then
              rust.fromRustupToolchainFile ./rust-toolchain.toml
            else if builtins.pathExists ./rust-toolchain then
              rust.fromRustupToolchainFile ./rust-toolchain
            else
              rust.stable.latest.default.override {
                extensions = [ "rust-src" "rustfmt" ];
              };
        })
      ];
      supportedSystems = [ "x86_64-linux" "aarch64-linux" "x86_64-darwin" "aarch64-darwin" ];
      forEachSupportedSystem = f: nixpkgs.lib.genAttrs supportedSystems (system: f {
        pkgs = import nixpkgs { inherit overlays system; };
      });
    in
    {
      devShells = forEachSupportedSystem ({ pkgs }: {
        default = pkgs.mkShell {
          packages = with pkgs; [
            rustToolchain
            openssl
            pkg-config
            cargo-deny
            cargo-edit
            cargo-watch
            rust-analyzer

            qemu
            pkgsCross.aarch64-multiplatform-musl.stdenv.cc
          ];

          CARGO_BUILD_TARGET = "x86_64-unknown-linux-musl";
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_LINKER = "${pkgs.pkgsCross.aarch64-multiplatform-musl.stdenv.cc.targetPrefix}cc";
          CARGO_TARGET_AARCH64_UNKNOWN_LINUX_MUSL_RUNNER = "qemu-aarch64";
        };
      });
    };
}
```
ref: https://github.com/oxalica/rust-overlay/issues/114#issuecomment-1416287080

**Comment by oxalica** [comment]
> cross-aarch64 example to a flake

I don't think the current flake design supports cross-compilation without re-importing nixpkgs with a custom `config`, which also opt-out flake benefits like eval-caching. There are issues https://github.com/NixOS/nix/issues/5157 and [blogs](https://jade.fyi/blog/flakes-arent-real/) about the current state of cross-compilation for flakes.

Alternatively to the re-importing with `config`/`overlay` solution, we can also provide a builder interface for rust-overlay to be used as `(rust-overlay.lib.mkRustBin nixpkgs.legacyPackages.pkgsCross.aarch64-multiplatform).stable.latest`. This will re-instantiate only rust-overlay packages rather than all nixpkgs packages. It still cannot use eval-cache and will instantiate every time for each flake input using rust-overlay, but at least it's the lesser of two evils.

The second solution is also mentioned in https://github.com/oxalica/rust-overlay/issues/94#issuecomment-2071471458

**Comment by holly-hacker** [comment]
Thanks for the fix!
