### ISSUE TITLE
wrong nightly rust version

### ISSUE THREAD

**Issue by lolbinarycat** [oxalica/rust-overlay#176]
```console
$ nix shell github:oxalica/rust-overlay#rust-nightly_2024-06-01
$ cargo version
cargo 1.80.0-nightly (431db31d0 2024-05-28)
```

this seems quite bad?

**Comment by lolbinarycat** [comment]
locked version:
```console
$ nix shell github:oxalica/rust-overlay/ab69b67fac9a96709fbef0b899db308ca714a120#rust-nightly_2024-06-01
$ cargo version
cargo 1.80.0-nightly (431db31d0 2024-05-28)
```

**Comment by oxalica** [comment]
The URL is correct and it's producing the same result as `rustup`'s `nightly` toolchain. `rustc --version` also shows the expected result.

I guess it's because `nightly` is shipped based on the rust-lang/rust repo itself, which contains a snapshot of all tools (including `cargo`). And not every tool is updated every day, their submodule is updated in a batch manner.
The last cargo update PR seems to be just after the nightly time https://github.com/rust-lang/rust/pull/125835, and the second last one is merged on 2024-05-28 https://github.com/rust-lang/rust/pull/125682 which is what you see.
