### ISSUE TITLE
Configuring with clion

### ISSUE THREAD

**Issue by KaiserKarel** [oxalica/rust-overlay#24]
I'm a big nix noob, trying to configure nix-shell with Clion
```
let
  oxalica_overlay = import (builtins.fetchTarball
    "https://github.com/oxalica/rust-overlay/archive/master.tar.gz");
  nixpkgs = import <nixpkgs> { overlays = [ oxalica_overlay ]; };

in with nixpkgs;
pkgs.mkShell {
    # nativeBuildInputs is usually what you want -- plugins you need to run
    nativeBuildInputs = [
        firefox
	jetbrains.clion
        docker
        docker-compose
        openssl.dev
        gcc

        rust-bin.stable.latest.rust
        rustup
        protobuf
	buf
        rustPackages.clippy
        pkg-config
    ];
}
```

Clion is unable to find the rust toolchain and stdlib with this config. Adding rustup makes it all work. Does adding rustup conflict with the overlay?

**Comment by oxalica** [comment]
Your configuration seems fine. Though it's not recommended to use rust-overlay and `rustup` together since it may collides.

Sorry but I don't use Clion and don't know how do it find rust toolchain.
I guess Clion may depend on `rustup` command or some `rustup` features. Note that `rustup` provides its own fake `rustc`, `cargo`, etc, to handle special arguments like `+stable`, before passing them to real `rustc` and `cargo`. Some programs may relies on this behavior, which is not supported by our vanilla toolchain from upstream.

**Comment by seam345** [comment]
I managed to get it working, I may have missed a simpler way but also quite new to nix. It does appear the jetbrains plugin would prefer rustup though

The toolchain autofilled for me when starting the IDE from the command line in the nix-shell.
If it doesn't auto fill you can manually enter `/nix/store/<hash>-rust-default-<version>/bin`

however I had issues with the standard library until i found this [this comment](https://github.com/intellij-rust/intellij-rust/issues/2211#issuecomment-359150900) and realised I needed rust-src.  
You will need to add `rust-bin.stable.latest.rust-src` to your shell.nix. However as this doesn't auto fill, I suspect there is some magic env variable I can set to fix this, the path you need to manually add is `/nix/store/<hash>-rust-src-<version>/lib/rustlib/src/rust`

After that all should work \o/

for completeness a copy of my shell.nix
```
let
  oxalica_overlay = import (builtins.fetchTarball
    "https://github.com/oxalica/rust-overlay/archive/master.tar.gz");
  nixpkgs = import <nixpkgs> { overlays = [ oxalica_overlay ]; };

in with nixpkgs;

stdenv.mkDerivation {
  name = "rust-env";
  buildInputs = [ 
    rust-bin.stable.latest.default
    rust-bin.stable.latest.rust-src
        
    # Add some extra dependencies from `pkgs`
    pkg-config 
    openssl
    linuxPackages.perf
    curl
    gnupg
  ];  

  # Set Environment Variables
  RUST_BACKTRACE = 1;

}
```
I have some additonal dependencies but as i havent tested without them so left them in. In theory you can remove the curl, gnupg, linuxPackages.perf, openssl, and pkg-config 

and a screen shot of my intelij rust settings page
![image](https://user-images.githubusercontent.com/22852285/129943918-fff99806-0dad-4085-9307-6e655926b6fb.png)

**Comment by oxalica** [comment]
Generally you should not explicitly use a single component like `rust-bin.stable.latest.rust-src`, since it may not work well with other components without some special treatment.

It's preferred to use `(rust-bin.stable.latest.default.override { extensions = [ "rust-src" ]; })` (don't forget the parenthesis). Then it contains rustc, cargo, etc. and also rust-src all in a single derivation.

Also it's not reliable to write nix store paths directly in your config file (`.idea/workspace.xml`), since it's hard to maintain and the referenced path may be deleted by garbage collection (Nix doesn't know it's in use).
I'd like to `nix-build` the aggregated derivation to produce a symlink (usually named `result`), and reference the path through the symlink like `../result/lib/rustlib/src/rust`. As long as you doesn't move or delete the symlink produced by `nix-build`, it will be stored as a GC root to prevent itself from deleting.

BTW: If you think this issue is considered resolved, please close it.
