### ISSUE TITLE
Cannot use `complete` profile on latest stable

### ISSUE THREAD

**Issue by abbec** [oxalica/rust-overlay#39]
Trying to use the `complete` profile on rust `1.52.1` gives me this error:

```
error: Component resolution failed for rust-complete-1.52.1
- note: available extensions are cargo, clippy, clippy-preview, llvm-tools-preview, miri, miri-preview, reproducible-artifacts, rls, rls-preview, rust-analysis, rust-analyzer-preview, rust-docs, rust-mingw, rust-src, rust-std, rustc, rustc-dev, rustc-docs, rustfmt, rustfmt-preview
- Host component `rust-analyzer-preview` doesn't support target `x86_64-apple-darwin`
- Host component `miri-preview` doesn't support target `x86_64-apple-darwin`
```

**Comment by abbec** [comment]
Should note that the `rust` target works

**Comment by oxalica** [comment]
`complete` profile [should never be used](https://rust-lang.github.io/rustup/concepts/profiles.html#profiles). `rust-analyzer-preview` is indeed not available in that release. You should use `default` profile and add whatever extensions you need. (Assuming you don't actually need `rust-analyzer-preview`, or you should try `nightly`)

I'm not sure about the current behavior of rustup when some components are unavailable. Does it simply ignore them and just install available ones? It seems kind of surprising, since after an update, some binaries may silently disappear without evaluation or build error. This behavior is unacceptable to me.

**Comment by abbec** [comment]
Yeah, somehow a (kinda old) version of rust-analyzer shows up when using the `rust` profile. I am fine with bringing it in through nightly but just wanted to know what was expected to work since the `rust` profile somehow does?

**Comment by oxalica** [comment]
`rust` is the bundle provided by upstream containing uncertain components, which is used by https://github.com/mozilla/nixpkgs-mozilla. Not sure if they are all up-to-date.
Currently `rustup` doesn't use the `rust` bundle. It by default fetches individual components (you can see multiple progress bar) just as what we do in the `default` or `minimal` profile.

**Comment by oxalica** [comment]
BTW: `rust-analyzer` is available and updated (approximately) weekly in nixpkgs. I think it's enough for most cases. Note that `rust-analyzer` itself doesn't rely on rustc internals or the version of builder rustc, you can simply [override `rustSrc`](https://github.com/NixOS/nixpkgs/blob/a2c3ea5bf825348322c901358b155f651d8ed699/pkgs/development/tools/rust/rust-analyzer/wrapper.nix#L5) to the any nightly of stable std source from `rust-overlay`.

**Comment by abbec** [comment]
Yeah we do that already, thanks for the info! :)
