### ISSUE TITLE
Brainstorming: A way to build a rustup-compatible toolchain set?

### ISSUE THREAD

**Issue by antifuchs** [oxalica/rust-overlay#49]
I'm developing in rust in various repos (many of which won't include any nix shell definitions) , and really like the way you can run, e.g., `cargo +nightly test` to run tests with a specific toolchain. Now I just realized that since rust-overlay already provides the toolchains in a very rustup-alike way, and that the two might be compatible; are you aware of a way to build a symlink tree to the rust toolchains provided by rust-overlay that allows the rustup stub binaries to use them? Otherwise, I might explore building something like it.

**Comment by oxalica** [comment]
Do you mean to support `+nightly` or friends flags? That's sounds a bad idea. It can referring arbitrary version, which need to invoke `nix` during the `rustc` call:
1. It's slow.
2. Calling package manager to install program-decided packages when invoking compiler can be out of your control.
3. It break `nix`'s feature of development environment isolation.
4. It's so imperative and you cannot run `nix` inside `nix` now. This means you cannot use `rust-overlay` to package your crate if so (currently our toolchain can be used for `buildRustPlatform` and `buildRustPackage`).

I personally hate the behavior to let script auto-install random packages out of my control instead of knowing the whole dependency closure in a single requirement file at once (like what `shell.nix` does).

**Comment by antifuchs** [comment]
Ergh, sorry I couldn't reply in time: None of what you seem to have read into this is what I meant at all. I guess the `+nightly` I gave as an example may have thrown my meaning off. Let's try again!

Here's what I had in mind to do:

1. provide a function to system / devShell builders, say `collectRustupVersions` that constructs a directory of symlink trees that  compatible with [`$RUSTUP_HOME/toolchains/`](https://rust-lang.github.io/rustup/environment-variables.html).
2. Allow that function to take a few methods of specifying the (very specific) rust versions to include in the symlink tree - I imagine it should be possible to use `rust-toolchain.toml` files and nix-specified toolchain versions.
3. expose an environment-creation function for shell setups that sets `RUSTUP_HOME`, for use in shell.nix / flake `devShell` clauses.

All that I hope for here is to pin rust in a system/shell config that ties in nicely with a variety of repositories' `rust-toolchain.toml` selection, without having to rely on the rust version manager doing any work. As I mentioned, the rust-overlay seems to be almost there (it can read the toolchain version and provides a reasonable-looking installation, for one).

**Comment by psionic-k** [comment]
We build shells in cargo2nix using `pkgs.mkShell` and taking all the propagated inputs.

In cargo2nix, this goes quite a bit farther because we know all of the dependencies `rustpkgs.noBuild.workspace`, including the environment, C libs, stdenv for linking and so on.

My cross compiling branch / PR makes the creation of this `devShell` attribute into a first-class part of our overlay functions:  https://github.com/cargo2nix/cargo2nix/pull/214/commits/25215dc74cdb6770d0bfa9d177e2b0a1f851edfe

> All that I hope for here is to pin rust in a system/shell config that ties in nicely with a variety of repositories' rust-toolchain.toml selection, without having to rely on the rust version manager doing any work. 

I think what you really want is a shell per-repository and the direnv integration with flakes.  Cargo2nix's top level flake.nix defines a `devShell` and the `.envrc` is the direnv integration (not that typing `nix develop` in bash is hard).  Shell per repo is definitely the way to go if the concern is juggling multiple toolchains.

Since there is toolchain file support, you can even create these shells with just:
`rust-bin.fromRustupToolchainFile ./rust-toolchain`

**Comment by dmoonfire** [comment]
@antifuchs: I'm curious if what you are describing is related to my problem. I'm using Intellij Ultimate for my development studio, but it complains that it can't connect to the sources without `rustup`:

> Can not attach stdlib sources automatically without rustup

Is what you are talking about basically creating the shell of what is needed to get `rustup` to provide information like that but still be in a controlled environment driven by the flake?

**Comment by oxalica** [comment]
> Here's what I had in mind to do:
> 
>     1. provide a function to system / devShell builders, say `collectRustupVersions` that constructs a directory of symlink trees that  compatible with [`$RUSTUP_HOME/toolchains/`](https://rust-lang.github.io/rustup/environment-variables.html).
> 
>     2. Allow that function to take a few methods of specifying the (very specific) rust versions to include in the symlink tree - I imagine it should be possible to use `rust-toolchain.toml` files and nix-specified toolchain versions.
> 
>     3. expose an environment-creation function for shell setups that sets `RUSTUP_HOME`, for use in shell.nix / flake `devShell` clauses.

I still cannot find a reasonable motivation to simulate `rustup`'s directory structure. Not only is it not Nix-y, but also the `rustup` structure itself is internal and considered unstable. Let alone there is almost no program except `rustup` itself relying on this structure.

If you want to use multiple version of `rust` toolchain, there are plenty ways to achieve it with Nix, by using variables other than PATH (eg. `RUSTC_OLD = "${rust-bin.stable."1.49.0".default}/bin/rustc"`), symlink helpers from `nixpkgs` like `linkFarm` or `symlinkJoin`, or creating wrapper scripts yourself.

Close as not planned.

**Comment by dmoonfire** [comment]
There are external programs that do make some assumptions based on the `.rustup` file. For example, IntelliJ appears to use the contents of `rustup show` and `rustup toolchain` to figure out default and installed locations. And the tooling does appear create softlinks for a consistent directory structure, which is used by the IDEs. (Looking at `rustup toolchain help link` is where I got that assumption).

Having the flake generate the minimum to set up and call `rustup toolchain link propery-name-of-toolkit /nix/store/*path` works might be helpful to generate automatically via this flake. Writing something that searches the /nix/store by hand and updating it seems like a non-trivial task.

Though, it would make sense to have a environment-specific `.rustup` file to do that, to see the individual sets isolated.
