### ISSUE TITLE
rustfmt preview is not installed

### ISSUE THREAD

**Issue by npajkovsky** [oxalica/rust-overlay#56]
Hey,

I have in my home-manager 

```
    (pkgs.rust-bin.stable.latest.default.override {
      targets = [ "x86_64-apple-darwin" ];
      targetExtensions = [ "rust-docs" ];
      extensions = [ "rustfmt-preview" ];
    })

    (pkgs.rust-bin.stable.latest.default.override {
      targets = [ "wasm32-unknown-unknown" ];
      extensions = [ "rust-std" ];
    })
```

I want to have two architectures `aarch64-apple-darwin` and `wasm32-unknown-unknown`, which works fine, but I would like to also have `rustfmt-preview`.

But I'm stuck with the stable version
```
-> % rustfmt --version
rustfmt 1.4.37-stable (59eed8a2 2021-11-01)
```

Am I doing something wrong?

**Comment by oxalica** [comment]
In your config `rust-bin.stable.latest` is used, so of course it's from stable toolchain.

The component name `rustfmt-preview` is just the same as `rustfmt` since it's now stable. In early years, `rustfmt` is under development, and to alarm users, there is only `rustfmt-preview` and no `rustfmt`.

To use nightly rustfmt, you need to retrieve it from nightly channel.
- To select it from a specific nightly date:
  `rust-bin.nightly."2021-10-26".default.override { extensions = [ "rustfmt" ]; }`
- To select the latest one with rustfmt available. (Yes, `rustfmt` may be broken on some dates, this function will auto-skip them)
  `rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override { extensions = [ "rustfmt" ]; })`

Also note that you seems to use two toolchain sets together, this results in only the first one available. You need to merge them and only have a single toolchain in global environment.
If you need both stable and nightly, it's better to write `shell.nix` per project and enter `nix-shell` to make a specific toolchain available.

**Comment by npajkovsky** [comment]
Thanks for the explanation.
