### ISSUE TITLE
Question: operability with +nightly commands

### ISSUE THREAD

**Issue by FintanH** [oxalica/rust-overlay#66]
Hey :wave: 

I currently ran into an issue where a repo that I work on started using the following command:
```
cargo +nightly fmt -- --check
```
but because the `+nightly` isn't being recognised. I noticed your comment here https://github.com/oxalica/rust-overlay/issues/49#issuecomment-918521120, so I'm guessing this might not be possible to interop with? Is there any way I can work around this?

My `shell.nix` looks like:
```nix
let
  nixpkgs = import <nixpkgs> {};
  stable = nixpkgs.rust-bin.stable.latest.default;
  rust = stable.override {
    extensions = [ "rust-src" "rust-analysis" ];
  };
in
  with nixpkgs;
  mkShell {
    name = "rust";
    buildInputs = [
        cargo-deny
        cargo-expand
        cargo-watch
        cmake
        openssl
        pkgconfig
        ripgrep
        rust
    ];
  }
```

Thanks for any help you can provide :blush:

**Comment by oxalica** [comment]
It's no impossible. Instead, it's quite simple to achieve it via wrapper shell scripts. If you want to pin `+nightly` to some specific version, like `2021-12-01`. You can do it now by creating a wrapping script of `cargo` and `rustc`, checking the arguments, and dispatching them to `"${rust-bin.nighlty.<whatever>.default}/bin/cargo"`. This is actually how `rustup` did: `rustup` installs fake `rustc`, `cargo` and etc to invoke real one from other places using special arguments.

I'm not in favor of this approach. As I listed in the issue you linked. Mainly because
1.  `+foo` is not actually a things recognizable by official rust components. It's a `rustup` arguments (see above).
2. We prefer Nix to do the version management and create isolated development environment for different projects. We don't need another thing to do a version dispatch, which can only mess things up, eg. some random scripts calling different rust versions in the same environment, causing cache inconsistency.

Before any significant reasons being raised, I'll mark this as wont-fix.

**Comment by FintanH** [comment]
Thanks for the response @oxalica :blush: 

I tried experimenting with dropping myself into a shell with the nightly binary and running `cargo fmt`. For some reason it still gave out about the unstable options we're using in our `rustfmt.toml`. However, if I do `nix-shell nightly.nix --run "cargo fmt"`, it works perfectly.

So, I think that'll be my workaround. It's just unfortunate we rely on some (questionably) unstable options. Feel free to close this question :)

**Comment by oxalica** [comment]
> However, if I do nix-shell nightly.nix --run "cargo fmt", it works perfectly.

You can try this,
```nix
mkShell {
  packages = [
    rust-bin.nightly."2021-12-02".rustfmt # The former rustfmt and cargo-fmt override the latter in `packages`.
    rust-bin.stable.latest.default # Use other components from stable.
  ];
}
```

Also you can try [direnv](https://github.com/direnv/direnv) to automatically enter `nix-shell` environment when `cd` into a directory.

**Comment by FintanH** [comment]
> You can try this,

Excellent, that seems to work a charm! Now I just need to convince my editor to use that binary :)

> Also you can try direnv to automatically enter nix-shell environment when cd into a directory.

Unfortunately, we're using stable for everything else. So, I'm using direnv to drop me into the shell with the stable release and then need the nightly formatter. Software amirite?!

Thanks for all the pointers, I really appreciate it!

**Comment by NickHu** [comment]
> > However, if I do nix-shell nightly.nix --run "cargo fmt", it works perfectly.
> 
> You can try this,
> 
> ```nix
> mkShell {
>   packages = [
>     rust-bin.nightly."2021-12-02".rustfmt # The former rustfmt and cargo-fmt override the latter in `packages`.
>     rust-bin.stable.latest.default # Use other components from stable.
>   ];
> }
> ```
> 
> Also you can try [direnv](https://github.com/direnv/direnv) to automatically enter `nix-shell` environment when `cd` into a directory.

Indeed this is a nice way to use nightly rustfmt with an otherwise stable toolchain; do you know of any ways to do the same thing with clippy instead? It has issues if you try to do it this way, like:

```
error[E0786]: found invalid metadata files for crate `std`
  |
  = note: invalid metadata version found: /nix/store/c8irbllc1mn1rpsrn96wpx83wdykhs8n-rust-std-1.58.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd_detect-0ddec007a0883060.rlib
  = note: invalid metadata version found: /nix/store/c8irbllc1mn1rpsrn96wpx83wdykhs8n-rust-std-1.58.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4c74cbab78ec4891.rlib
  = note: invalid metadata version found: /nix/store/c8irbllc1mn1rpsrn96wpx83wdykhs8n-rust-std-1.58.1-x86_64-unknown-linux-gnu/lib/rustlib/x86_64-unknown-linux-gnu/lib/libstd-4c74cbab78ec4891.so
```

I suspect it's looking at the crate build artifacts built with stable, and that's somehow incompatible with nightly clippy. I wonder if rustup is able to sidestep this issue even.

**Comment by oxalica** [comment]
@NickHu

> I suspect it's looking at the crate build artifacts built with stable, and that's somehow incompatible with nightly clippy. I wonder if rustup is able to sidestep this issue even.

It seems to be a cache mismatch, like compiling with one version of rustc and recompile later with another version. Please `cargo clean` and try to compile again.
If the issue still exists, please open an issue and show reproduction steps.
