### ISSUE TITLE
How to access documentation

### ISSUE THREAD

**Issue by AndrewKvalheim** [oxalica/rust-overlay#80]
In a rustup installation the local documentation can be opened via:

```console
$ rustup doc
```

The overlay’s package also includes this documentation but it’s not clear to me how it’s intended to be found. For now I’ve exposed it via an ad hoc script:

```nix
pkgs.writeShellScriptBin "rust-doc" ''
  xdg-open '${pkgs.rust-bin.stable.latest.default}/share/doc/rust/html/index.html'
''
```

Is this the way to go or am I missing something?

**Comment by oxalica** [comment]
My approach is to install the default toolchain into a nix profile using `home-manager`, and then add this URL to my browser's bookmark list. Since we usually use a GUI browser to open HTML pages, not in a terminal.
```
file:///etc/profiles/per-user/<username>/share/doc/rust/html/std/index.html
```

If you install rust toolchains in the system environment (`configuration.nix`), that path should be (unchecked)
```
file:///run/current-system/share/doc/rust/html/std/index.html
```

Not sure if there's an better way for this.

**Comment by oxalica** [comment]
Close as won't fix, at least for now.

Adding the `file:///` URL to your browser bookmarks or writing a `xdg-open` script is good enough.
