### ISSUE TITLE
No matching package named "cfg-if" found for nightly rust

### ISSUE THREAD

**Issue by NoneTirex** [oxalica/rust-overlay#93]
Hello,
I am trying to use nightly toolchain of rust with rust-overlay, but I encountered a problem with error:
```
       > error: no matching package named `cfg-if` found
       > location searched: registry `crates-io`
       > required by package `test v0.0.0 (/nix/store/z1l62vpqfps23h7b78vpb187948krqcp-rust-default-1.63.0-nightly-2022-06-18/lib/rustlib/src/rust/library/test)`
       For full logs, run 'nix log /nix/store/krp3q7q5ivbdx6v4jgiqpk6izbf4qjj6-project-0.1.0.drv'.
```

I pass nightly toolchain in nativeBuildInputs for `rustPlatform.buildRustPackage` as below:
```
  nightly-toolchain = pkgs.rust-bin.selectLatestNightlyWith (toolchain: toolchain.default.override {
    extensions = [ "rust-src" ];
  });
```

The problem also appear for stable version.

**Comment by oxalica** [comment]
> For full logs, run 'nix log /nix/store/krp3q7q5ivbdx6v4jgiqpk6izbf4qjj6-project-0.1.0.drv'.

It's *your* project that is failed to build. Because usually, Nix derivations are not allowed to access network.

Please read [this section in Nixpkgs manual](https://nixos.org/manual/nixpkgs/stable/#compiling-non-rust-packages-that-include-rust-code) for more information, which explains how to use cargo vendor to fix your issue. Better to read the whole section [*17.31. Rust*](https://nixos.org/manual/nixpkgs/stable/#rust).
