### ISSUE TITLE
Make it possible to use an already imported nixpkgs instead of using overlays

### ISSUE THREAD

**Issue by yusdacra** [oxalica/rust-overlay#94]
Is there a need to use overlays? It would be much more preferable to be able to use an already instanced nixpkgs so I don't have to import another one just for `rust-overlay`.

EDIT: reasoning, https://zimbatm.com/notes/1000-instances-of-nixpkgs

**Comment by yusdacra** [comment]
BTW, `lib.fix (lib.extends (import sources.rust-overlay) (self: pkgs))` works as a workaround, but it is still not ideal since it still uses fixed-points as overlays do...

**Comment by oxalica** [comment]
Now we experimentally exported `default` toolchains as flake outputs in https://github.com/oxalica/rust-overlay/blob/3e95d6696b51f88b3ebfc7a21aefaeeb70a245bd/flake.nix#L46-L67

You can access toolchains without introducing another overlay but via flake outputs. Overriding them is also possible.
```
rust-overlay.packages.${system}.rust # = rust-bin.stable.latest.default
rust-overlay.packages.${system}.rust_1_45_0 # = rust-bin.stable."1.45.0".default
rust-overlay.packages.${system}.rust-nightly_2021-11-04 # = rust-bin.nightly."2021-11-04".default
```

I'm still not sure how to name these outputs. The `-` and `_` are annoying.

**Comment by oxalica** [comment]
1.5 years have been passed. Let me re-answer your question.

> Is there a need to use overlays?
> EDIT: reasoning, https://zimbatm.com/notes/1000-instances-of-nixpkgs

Yes, for the exact reason you provided: to avoid 1000 instances of nixpkgs.

I've been using flakes extensively and really suffers from the dependency management. It's easy to add an `inputs.brand-new-project.url = "whatever"` and boom, one more nixpkgs from their lockfile, on a random locked version, with or without security issues. The number of `nixpkgs` in your flake input closure can go exponentially when you have many heavy projects. Of course, `inputs.nixpkgs.follows = "nixpkgs";` can fix this, but it is really tedious to apply it on every dependency, and every dependency of dependencies, especially when some of your dependencies don't `follows` on their own.

But overlays do not have this mass overriding issue, because they carry no dependency. Each overlay behaves as a transformer and is composable with others. One can manually instantiate nixpkgs once in the final flake, eg. system configuration repo, by `pkgs = import <nixpkgs> { overlays = [ overlay1 overlay2 overlay3 /*...*/ ]; }`.

Flake does have many pros like easier CLI interface. But I think the design of flake favors locking down dependencies, and naturally don't like sharing except the user asked to do so for each one, which only worsens the too-many-nixpkgs problem.

**Comment by andrewhamon** [comment]
Hey @oxalica I found this issue while also searching for a way to avoid the use of overlays.

I think we all agree that many instances of nixpkgs is bad. But I also try to avoid overlays, because a single overlay can cause an unknowable number of packages to be rebuilt (i.e. suppose you overlaid a different version of gcc or clang, most software would have to be rebuilt).

It seems like rust-overlay is well behaved and doesn't change `pkgs.rustc`. But still, the API I would prefer would be something more like this:

```
rust-bin = rust-overlay.lib.mkRustBin pkgs;
```

rather than having to get `rust-bin` in an overlay.
